### PR TITLE
Update zh_CN-README.md

### PR DESCRIPTION
**Pull request by Jabaay**
- reworded a phrase
- updated the links to make it clear that it won't work otherwise unless already joined the discord

### CODE REVIEW

**Comment by Lacyway** [comment]
Is this one up to date?

**Comment by Jabaay** [comment]
> Is this one up to date?

Yup, I actually updated all the instances that contain the download and Discord links (where there're only 2 in the original README but in fact it should be 4)

**Comment by Lacyway** [comment]
> > Is this one up to date?
> 
> Yup, I actually updated all the instances that contain the download and Discord links (where there're only 2 in the original README but in fact it should be 4)

Can you fix the conflicts so that I can merge? Thanks!

**Comment by Jabaay** [comment]
> > > Is this one up to date?
> > 
> > 
> > Yup, I actually updated all the instances that contain the download and Discord links (where there're only 2 in the original README but in fact it should be 4)
> 
> Can you fix the conflicts so that I can merge? Thanks!

It should be fixed now, thanks.

**Pull request merged**
